# Generated by Django 3.1.2 on 2020-12-31 12:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(db_index=True, max_length=50, verbose_name='Тип оплаты')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateField(default=datetime.date.today, verbose_name='Дата заказа')),
                ('time_add', models.TimeField(default=datetime.datetime.now, verbose_name='Время заказа')),
                ('number', models.IntegerField(default=0, verbose_name='Номер заказа')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('shop', models.CharField(max_length=250, verbose_name='Магазин')),
                ('what_buy', models.TextField(blank=True, verbose_name='Что купить?')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('personal_info', models.BooleanField(default=True, verbose_name='Принимаю условия обработки персональных данных ')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='Цена')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery_form.payment', verbose_name='Оплата')),
            ],
        ),
    ]
