# Generated by Django 3.1.2 on 2020-11-18 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryform',
            name='date_add',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='deliveryform',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Цена'),
        ),
    ]
