# Generated by Django 3.1.2 on 2020-11-18 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_form', '0002_auto_20201118_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryform',
            name='time_add',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время заказа'),
        ),
    ]
