# Generated by Django 3.1.2 on 2020-11-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_form', '0003_deliveryform_time_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryform',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='deliveryform',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='Цена'),
        ),
    ]
